const express = require('express');
const router = express.Router();
const controller = require('../controller/products.controller');
const giayTreEm = require('../controller/products/giaybongdatreem.controller');
const giayAdidas = require('../controller/products/giayadidas.controller');
const giayCoNhanTao = require('../controller/products/giayconhantao.controller');
const newProduct = require('../controller/products/sanphammoi.controller');
const saleProduct = require('../controller/products/sanphamgiamgia.controller');
const giayCoTuNhien  = require('../controller/products/giaycotunhien.controller');
const giayFutsal = require('../controller/products/giayfutsal.controller');
const giayMizuno = require('../controller/products/giaymizuno.controller');
const giayPuma = require('../controller/products/giaypuma.controller');
const giayNike = require('../controller/products/giaynike.controller');
const linhKienTheThao = require('../controller/products/linhkienthethao.controller');
//const { route } = require('./cart.route');
//const { route } = require('./user.route');
 
router.get('/', controller.index);
router.get('/search', controller.search);
router.get('/newproducts', newProduct.newproducts);
router.get('/saleproducts', saleProduct.saleproducts);
router.get('/giaycotunhien', giayCoTuNhien.giaycotunhien);
router.get('/giayconhantao', giayCoNhanTao.giayconhantao);
router.get('/giaybongdatreem', giayTreEm.giaybongdatreem);
router.get('/giaybongdaadidas', giayAdidas.giaybongdaadidas);
router.get('/giayfutsal', giayFutsal.giayfutsal);
router.get('/giaymizuno',giayMizuno.giaymizuno);
router.get('/giaypuma',giayPuma.giaypuma);
router.get('/giaynike',giayNike.giaynike);
router.get('/linhkienthethao',linhKienTheThao.linhkienthethao);
module.exports = router;